import "./globals.css";
import Header from '@/components/Header';
import { Toaster } from 'sonner';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-neutral-100">
        <Header/>
        <Toaster/>
        {children}
      </body>
    </html>
  )
}
